[package]
name = 'raise_money'
version = '1.0.0'
upgrade_policy = "immutable"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
raise_money = "_"
aptos_framework = "0x1"